services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes: 
      - ./graphql-books/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./graphql-books/prod_mongo_data:/data/db
  
  express:
    image: library-backend
    build:
      context: ./graphql-books
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=mongodb://the_username:the_password@mongo:27017/the_database
    container_name: library-backend
    depends_on:
      - mongo

  nginx:
    build:
      context: ./library-frontend
      dockerfile: Dockerfile
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - express