services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes: 
      - ./graphql-books/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./graphql-books/mongo_data:/data/db
  
  express:
    image: library-backend-dev
    build:
      context: ./graphql-books
      dockerfile: dev.Dockerfile
    volumes:
      - ./graphql-books:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - MONGODB_URI=mongodb://the_username:the_password@mongo:27017/the_database
    container_name: library-backend-dev
    depends_on:
      - mongo

  app:
    image: library-frontend-dev
    build:
      context: ./library-frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./library-frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - VITE_BACKEND_URI=http://localhost:8080/api
      - VITE_WS_BACKEND_URI=ws://localhost:8080/api
    container_name: todo-frontend-dev
  
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - express